apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app
spec:
  type: LoadBalancer # This binds port 3000 to your Master Node IP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: api-gateway-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: borsok/api-gateway-app:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m" # Required for HPA
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          # Assuming default endpoints, adjust if your Node code needs specific URLs
          env:
            - name: INVENTORY_URL
              value: "http://inventory-app:8080"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: RABBITMQ_PASSWORD
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
