apiVersion: v1
kind: Service
metadata:
  name: billing-db
spec:
  ports:
    - port: 5432
  selector:
    app: billing-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
spec:
  serviceName: "billing-db"
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      initContainers:
        - name: init-and-fix
          image: borsok/billing-db:v1
          command:
            - "sh"
            - "-c"
            - "if [ ! -f /mnt/data/PG_VERSION ]; then cp -a /var/lib/postgresql/13/main/* /mnt/data/; fi; chown -R postgres:postgres /mnt/data && chmod 700 /mnt/data"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: billing-data
              mountPath: /mnt/data
      containers:
        - name: billing-db
          image: borsok/billing-db:v1
          ports:
            - containerPort: 5432
          env:
            - name: DB_NAME
              value: "billing_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: BILLING_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: BILLING_DB_PASSWORD
          volumeMounts:
            - name: billing-data
              mountPath: /var/lib/postgresql/13/main
  volumeClaimTemplates:
    - metadata:
        name: billing-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
