apiVersion: v1
kind: Service
metadata:
  name: billing-app
spec:
  ports:
    - port: 8080
  selector:
    app: billing-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: "billing-app"
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-app
          image: borsok/billing-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "billing-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "billing_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: BILLING_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: BILLING_DB_PASSWORD
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-secrets
                  key: RABBITMQ_PASSWORD
